### ISSUE TITLE
大佬，现在60s好像没显示全部的内容是为啥

### ISSUE THREAD

**Issue by zazjaya** [vikiboss/60s#11]
![image](https://github.com/user-attachments/assets/032ab3e3-8fe8-4b8e-945d-5843b2dcca0f)
![image](https://github.com/user-attachments/assets/a3a86ebc-ca28-424a-b05b-4ac06a18b0b3)

**Comment by vikiboss** [comment]
数据是来源于知乎的 [这个](https://www.zhihu.com/api/v4/columns/c_1715391799055720448/items?limit=2) 接口的 `data[0].content` 字段，这个字段是 html，60s api 内部进行解析的。

之前都是返回的完整的，但是最近好像返回的内容被截取了，没有完全返回. -.-

<img width="300" alt="image" src="https://github.com/user-attachments/assets/65fc1895-e6d5-4517-9fe4-3ed6aab37693">

**Comment by vikiboss** [comment]
已通过新增登录后的 Cookie 临时解决。

> 24 年 7 月份开始，知乎更新后新加的限制，参考 [这里](https://github.com/DIYgod/RSSHub/issues/16260)。
