### ISSUE TITLE
汇率

### ISSUE THREAD

**Issue by zhengkw614** [vikiboss/60s#12]
请问汇率接口的数据是多久更新一次？

**Comment by vikiboss** [comment]
数据源头是一天更新一次，60s API 的策略保持一致。

https://github.com/vikiboss/60s/blob/d0e4a0e2bd59b3aed7475d08cb7fb92dfd66b762/src/services/ext-rates.ts#L7

**Comment by vikiboss** [comment]
如果需要更及时的更新，可以自己去这个数据提供平台注册相关会员，使用付费 API，以获取更精细的更新粒度。

https://www.exchangerate-api.com/docs/free
