### ISSUE TITLE
【BUG】返回的数据未更新或者更新时间很晚

### ISSUE THREAD

**Issue by BennettChina** [vikiboss/60s#15]
我是8:30~9点去请求的接口，数据返回的是昨天的，现在看接口已经是今天的了，我明天再试一下吧，看看是官方数据没更新还是这边缓存的问题。

**Comment by vikiboss** [comment]
数据的源头就是一个知乎号，他是手动发的，早上 8-9 点左右，这个是正常现象。

**Comment by vikiboss** [comment]
<img width="585" alt="image" src="https://github.com/user-attachments/assets/ef7278af-05a3-44d2-8abc-00de4c479769">

时间不确定 https://zhuanlan.zhihu.com/p/10031765685

**Comment by BennettChina** [comment]
我看知乎的接口返回的时间戳是7:20左右，我还以为很早就更新了，原来如此。
