### ISSUE TITLE
请问下历史上的今天这个接口是哪里的服务呀？

### ISSUE THREAD

**Issue by RainMaker-Q** [vikiboss/60s#16]
看了下是请求的这个接口https://baike.deno.dev/today_in_history ， 域名看起来是 deno的，好奇这是哪里的服务呀

**Comment by vikiboss** [comment]
这是我写的另一个项目哈，性质类似，也是 API，仓库在 [这里](https://github.com/vikiboss/deno-functions)。

这个项目也是用 Deno 写的，很早了，部署在 Deno 官方的免费托管平台 [Deno Deploy](https://deno.com/deploy) 上。**\*.deno.dev** 是 Deno Deploy 免费分给项目的子域名，其实本质和这个 60s 是一样的，只不过 60s 配置了自定义域名 （60s.viki.moe），而这个 baike 没有，然后 60s 掉用了我这个项目的服务，聚合了一下 API。

**Comment by RainMaker-Q** [comment]
了解了，thx! ：）
