### ISSUE TITLE
接口挂了，老哥什么时候修复一下啊

### ISSUE THREAD

**Issue by musaart** [vikiboss/60s#3]
接口挂了，老哥什么时候修复一下啊

**Comment by vikiboss** [comment]
官方停更了，没办法，这是数据源。

https://zhuanlan.zhihu.com/p/665616411

**Comment by musaart** [comment]
可以换数据源么，https://zhuanlan.zhihu.com/p/669564268换这个

**Comment by vikiboss** [comment]
晚点看看，应该可以。

**Comment by vikiboss** [comment]
类型不一样，一个是专栏的文章列表，一个是普通的文章列表，可能得花点时间处理。

**Comment by xieliuhao** [comment]
微信公众号还在更新，能爬吗

**Comment by vikiboss** [comment]
找了下，正常途径得有微信的鉴权 key 才能拿，历史文章列表那个页面得微信内才能打开，估计也要什么验证信息，没事去深入研究了。

https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzU3MjYzNjc0Nw==#wechat_redirect

**Comment by vikiboss** [comment]
> 可以换数据源么，[https://zhuanlan.zhihu.com/p/669564268换这个](https://zhuanlan.zhihu.com/p/669564268%E6%8D%A2%E8%BF%99%E4%B8%AA)

可以，它创建了一个专栏，现在可以用它平替了，但是就是希望它后续不要停更

**Comment by vikiboss** [comment]
已修复。

- https://60s.viki.moe
- - https://60s.viki.moe/60s
