### ISSUE TITLE
可以增加抖音热榜吗？

### ISSUE THREAD

**Issue by Flionay** [vikiboss/60s#4]

**Comment by vikiboss** [comment]
得找找有没有数据源（没有复杂验证啥的），有数据源的话还是很好加的。

**Comment by vikiboss** [comment]
标记一下，有空就加。

https://www.douyin.com/aweme/v1/web/hot/search/list

**Comment by Flionay** [comment]
<img width="1270" alt="iShot2024-01-03_10 52 13" src="https://github.com/vikiboss/60s/assets/50234719/c807f8df-f2b6-4023-b887-fc928ad1fab9">

**Comment by vikiboss** [comment]
只收录官方接口确保稳定性

**Comment by vikiboss** [comment]
> <img alt="iShot2024-01-03_10 52 13" width="1270" src="https://private-user-images.githubusercontent.com/50234719/293824728-c807f8df-f2b6-4023-b887-fc928ad1fab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1OTU2OTIsIm5iZiI6MTcwNDU5NTM5MiwicGF0aCI6Ii81MDIzNDcxOS8yOTM4MjQ3MjgtYzgwN2Y4ZGYtZjJiNi00MDIzLWI4ODctZmM5MjhhZDFmYWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDAyNDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NjhjZDVmNGMyZmYzNWE2Mjk0NjEyMjQ3MzQ0YzlhY2U4YjM5MmNkMGUyNDhhN2YwMGJhMTJkNWQ1MjA2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-qNLIf3umTZ4H-myrA4rXv5UDSXjoUN0NKfnepe5IiQ">

看了一下，这个应该也只官方的

**Comment by vikiboss** [comment]
已添加并部署接口，并简化了返回的数据优化大小。

https://60s.viki.moe/douyin
