### ISSUE TITLE
获取内容缺失

### ISSUE THREAD

**Issue by Jaderi666** [vikiboss/60s#5]
获取内容部分缺失。加上微语，获取到的内容结果总计应该有16个列表，但偶尔只能获取到15个列表，特别容易缺失第2个列表

**Comment by vikiboss** [comment]
好的，等我有空看一看

**Comment by vikiboss** [comment]
已修复，同时此 API 已发布 v2 格式，规范 JSON 返回，可通过 `?v2=1` 参数开启，如：[https://60s.viki.moe/60s?v2=1](https://60s.viki.moe/60s?v2=1)

**Comment by Jaderi666** [comment]
感谢大佬快速的反应！
