### ISSUE TITLE
能否给“每天60秒读懂世界”加一个更新日期或时间戳？以便验证是请求数据当天的内容？（其实这应该是建议而不是问题）

### ISSUE THREAD

**Issue by Jaderi666** [vikiboss/60s#6]
出错场景：请求数据的时间早于数据更新时间，导致get到的“每天60秒读懂世界”其实是昨天的，所以能否麻烦大佬加一个数据更新日期（或时间戳）以便验证是请求数据当天的内容。非常希望大佬能实现这个建议，感谢

**Comment by vikiboss** [comment]
加 都可以加。
明天给你加

**Comment by Jaderi666** [comment]
感谢大佬！


发件人：Viki ***@***.***>
发送日期：2024-03-07 20:55:36
收件人：vikiboss/60s ***@***.***>
抄送人：
主 题：Re: [vikiboss/60s] 能否给“每天60秒读懂世界”加一个更新日期或时间戳？以便验证是请求数据当天的内容？（其实这应该是建议而不是问题） (Issue #6)

加 都可以加。
明天给你加

**Comment by vikiboss** [comment]
干活搞忘了😭

**Comment by vikiboss** [comment]
<img width="897" alt="image" src="https://github.com/vikiboss/60s/assets/53367348/653aad49-fb3d-412a-8d8f-759a17b0b28b">

**Comment by vikiboss** [comment]
想起来了，现在给你加了 🥹，请使用 v2, https://60s.viki.moe/60s?v2=1

**Comment by Jaderi666** [comment]
刚刚试用了，效果杠杠的，哈哈。

**Comment by Jaderi666** [comment]
> 干活搞忘了😭

现在还有活干，羡慕不已
